### ISSUE TITLE
[이미지] 이미지 관련 기능 구현

### ISSUE THREAD

**Issue by yeonwoo1125** [re-prife/back-end#100]

**Comment by m04j00** [comment]
연우님 백번째 이슈 축하드려요 ^^ 한턱 쏘세요

**Comment by yeonwoo1125** [comment]
다들 감사합니다^^ 축하 턱은 민지님의 카드를 통해 제가 쏘도록 하겠습니다!!

**Comment by m04j00** [comment]
> 다들 감사합니다^^ 축하 턱은 민지님의 카드를 통해 제가 쏘도록 하겠습니다!!

취업한 사람이 취준생 카드까지 뺴앗다니 ㅠ.ㅠ
