### ISSUE TITLE
[식재료] 식재료를 직접 입력해서 추가하는 기능

### ISSUE THREAD

**Issue by m04j00** [re-prife/back-end#3]
## 기능 설명

* 식재료를 직접 작성하여 등록하는 기능

>[POST] groups/{groupId}/iningredients

### request
```json
{
	"ingredientName" : "salad source",
	"ingredientSaveType" : "ROOM_TEMP",
	"ingredientPurchaseDate" : "2022-02-02", 
	"ingredientExpirationDate" : "2023-02-02", 
	"ingredientCategory" : "SEASONING", 
	"ingredientCount " : "1개", 
	"ingredientMemo" : "메모메모"
}
```

### response
200 - Ok
    식재료 추가가 정상적으로 처리된 경우

409 - Conflict
    모든 정보가 제대로 들어오지 않았을 경우

404 - Not Found
   해당하는 그룹이 존재하지 않는 경우

## 소요 시간
- 예상 완료 시간 : H
- 실제 소요 시간 : H

## 진행 사항

- [x] 그룹 존재 여부 
- [x] 폼 형식 맞는지 여부
- [x] 식재료 추가
- [x] 유통기한, 구매 날짜 처리(String, date, localdatetime)
- [x] enum DB에 저장(숫자, 변수 이름,  멤버 변수)
- [x] 식재료 카운트 int -> String 변경
- [x] 경로에 s 붙이기

**Comment by yeonwoo1125** [comment]
## 기능 설명

* 식재료를 직접 작성하여 등록하는 기능

>[POST] groups/{groupId}/iningredients

### request
```json
{
	"ingredientName" : "salad source",
	"ingredientSaveType" : "냉동",
	"ingredientPurchaseDate" : "2022-02-02", 
	"ingredientExpirationDate" : "2023-02-02", 
	"ingredientCategory" : "source", 
	"ingredientCount " : "1개", 
	"ingredientMemo" : "메모메모"
}
```

### response
```
{
    "completeCheck" : "true/false"
}
```
200 - Ok
    식재료 추가가 정상적으로 처리된 경우

409 - Conflict
    모든 정보가 제대로 들어오지 않았을 경우

404 - Not Found
   해당하는 그룹이 존재하지 않는 경우

Exception
SaveType이 정의된 enum이 아닌 경우
유통기한이 구매 날짜보다 앞선 경우


## 소요 시간
- 예상 완료 시간 : H
- 실제 소요 시간 : H

## 진행 사항
